print("Enter The Name of Student")
name=input()
Ko=open("test.txt","rt")
print("\n")
Ko.close()
Fo=open("test.txt","a")
Fo.write(name)
Fo.close()
Ro=open("test.txt","rt")
print(Ro.read()," \n")
Ro.close()