print("Enter The Marks in Physics")
phy = int(input())
print("Enter The Marks in Chemistry")
chem=int(input())
print("Enter The Marks in Mathematics")
math=int(input())
print("Enter The Marks in Computer")
com=int(input())
print("Enter The Marks in English")
eng=int(input())
marks=[phy,chem,math,com,eng]
print("Maximum Marks = ",max(marks))
print("Minimum Marks = ",min(marks))
print("Average Marks = ", sum(marks)/(len(marks)))